config/routes.rb
Rails.application.routes.draw do
  
  get 'callback' => 'welcome#callback'
  
  post 'pushbullet/push_random_note' => 'pushbullet#push_random_note', :as => :push_random_note
  post 'pushbullet/push_note' => 'pushbullet#push_note', :as => :push_note
  get 'pushbullet' => 'pushbullet#index'
  
  get 'notes' => 'notes#index', :as => :notes

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/notes_controller.rb
require 'one_note_sharer' # see lib/one_note_sharer.rb
require 'pushbullet_api' # see lib/pushbullet.rb

include ApplicationHelper

class NotesController < ApplicationController
  before_action :require_onenote_login
  
  def index
    @oneNoteWeb_url = nil
    @response_code = nil
    @note = nil
    @has_pb_access_token = !pb_access_token.blank?
    @has_access_token = !access_token.blank?
    @onenote_revoke_url = ONENOTE_CONFIG['revoke']
    @pushbullet_revoke_url = PUSHBULLET_CONFIG['revoke']

    
    onenote_client = OneNoteSharer.new
    pushbullet = PushbulletAPI.new
    is_pushbullet_req = false;

    result = onenote_client.get_pages_in_section(access_token)
    @notes = result
    
#    rescue Exception => e
#      if !is_pushbullet_req
#        @response = e.response
#        @response_code = e.http_code
#        @response_headers = @response.headers
#      end
    
  end
  
  private 
  
  def require_onenote_login
    unless !access_token.blank?
      flash[:error] = "OneNote must be logged in to view notes. Please login below."
      redirect_to root_path # halts request cycle
    end
  end
end

app/controllers/pushbullet_controller.rb
require 'one_note_sharer' # see lib/one_note_sharer.rb
require 'pushbullet_api' # see lib/pushbullet.rb

include ApplicationHelper

class PushbulletController < ApplicationController
  def index
    pushbullet = PushbulletAPI.new
    token_set = pushbullet.handle_callback_request(params)
    if token_set.present?
#      expire_in = "Fri, 31 Dec 9999 23:59:59 GMT"
      expire_in = 604800.seconds.from_now # the token doesn't expire lets set the cookie a week long at a time
      cookies['pb_access_token'] = { :value => token_set['access_token'], :expires => expire_in }
    end
#    debugger
    redirect_to root_path
  end

  def push_note
    pushbullet = PushbulletAPI.new
    result = pushbullet.push_page pb_access_token, params[:title], params[:body], params[:url]  # correct note body format was assigned to params 
    redirect_to notes_path
  end

  def push_random_note
    onenote_client = OneNoteSharer.new
    access_token = cookies['access_token']
    notes = onenote_client.get_pages_in_section(access_token)
    
    prng = Random.new
    rand_index = prng.rand(notes.length)  # get me a random number between 0 and total notes
    note = notes[rand_index]  # use that number to select a note
	pushbullet = PushbulletAPI.new
    pb = pushbullet.push_page pb_access_token, note[:title], note[:body][:text], note[:url] # note we have to specify the note body format
    redirect_to notes_path
  end
end

app/controllers/welcome_controller.rb
require 'one_note_sharer' # see lib/one_note_sharer.rb
require 'pushbullet_api' # see lib/pushbullet.rb

include ApplicationHelper

class WelcomeController < ApplicationController
  @resourse_url

  def index
    # OneNote
    @auth_url = auth_url
    @has_access_token = !access_token.blank?
    @onenote_revoke_url = ONENOTE_CONFIG['revoke']
    
    # Pushbullet
    @pushbullet_auth_url = pushbullet_auth_url
    @has_pb_access_token = !pb_access_token.blank?
#    debugger
    @pushbullet_revoke_url = PUSHBULLET_CONFIG['revoke']
  end
  
  def callback
    onenote_client = OneNoteSharer.new
    token_set = onenote_client.handle_callback_request(params)
    if token_set.present?
      expire_in = token_set['expires_in'].to_i
      cookies['access_token'] = { :value => token_set['access_token'], :expires => expire_in.seconds.from_now }
      cookies['authentication_token'] = { :value => token_set['authentication_token'], :expires => expire_in.seconds.from_now }
      cookies['scope'] = { :value => token_set['scope'], :expires => expire_in.seconds.from_now }
      refresh_token = token_set['refresh_token']

      onenote_client.save_refresh_token(refresh_token) if refresh_token.present?
    end
  end
  
end

app/helpers/application_helper.rb
require 'pushbullet_api' # see lib/pushbullet.rb

module ApplicationHelper
  def pb_access_token
    pb_access_token = cookies['pb_access_token']
#    session['pb_access_token'].nil? ? '' : session['pb_access_token'][:value]
  end

  def pushbullet_auth_url
    pushbullet = PushbulletAPI.new
    pushbullet_auth_url = pushbullet.auth_url
  end

  def access_token
    access_token = cookies['access_token']
  end

  def auth_url
    onenote_client = OneNoteSharer.new
    auth_url = onenote_client.auth_url
  end
  
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Notifyer"
    
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pushbullet_helper.rb
module PushbulletHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <!-- Add to homescreen for Chrome on Android -->
  <meta name="mobile-web-app-capable" content="yes">
  <link rel="icon" sizes="192x192" href="images/touch/chrome-touch-icon-192x192.png">

  <!-- Add to homescreen for Safari on iOS -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Material Design Lite">
  <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png">

  <!-- Tile icon for Win8 (144x144 + tile color) -->
  <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
  <meta name="msapplication-TileColor" content="#3372DF">
  
  <link href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.brown-blue.min.css" />
<!--  <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.blue-red.min.css" />-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="mdl-color--grey-100">
<% flash.each do |message_type, message| %>
<div class="mdl-card mdl-shadow--2dp flash-card">
  <div class="mdl-card__title mdl-card--expand">
    <h4>
      <%= message %>
    </h4>
  </div>
<!--
  <div class="mdl-card__actions mdl-card--border">
    <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
      Add to Calendar
    </a>
  </div>
-->
</div>
<% end %>
<%= yield %>
<!--<%= debug(params) if Rails.env.development? %>-->
<script src="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js"></script>
  <%= render 'partials/ga' %>
</body>
</html>

app/views/notes/_about.html.erb
<div class="mdl-layout__tab-panel" id="about">
  <section class="section--center mdl-grid mdl-grid--no-spacing">
    <div class="mdl-cell mdl-cell--12-col">
      <h4>About</h4>
      <p>
        Notifyer is a proof of concept solution to a problem I've been thinking about for a long time. Namely:
      </p>
      <ul>
        <li>How do I get a daily quote from my curated collection? </li>
        <li>How can I effortlessly resurface a buried quote so I can re-apply it's inspiration and lessons to the present? </li>
      </ul>
      <p>
         Using Microsoft's OneNote as a datastore, Notifyer utilizes OneNote's API to retrieve notes from a given section. 
         A note is then selected to be pushed to your devices via Pushbullet's API.
      </p>
      <p>
        The ideal use case is to schedule Notifyer's <em><strong>random</strong></em> method to be invoked periodically. 
        However for the purposes of this demo, users can select a note to be pushed immediately.
      </p>
      <% if @has_pb_access_token && @has_access_token %>
        <p>Try pushing the random note button below. </p>
      <% end %>
    </div>
  </section>
</div>

app/views/notes/_help.html.erb
<div class="mdl-layout__tab-panel" id="help">
  <section class="section--center mdl-grid mdl-grid--no-spacing">
    <div class="mdl-cell mdl-cell--12-col">
      <h4>Help</h4>

      <ul class="toc">
<!--        <h4>Contents</h4>-->
        <a href="#lorem1">Why don't I see any notes?</a>
        <a href="#lorem2">I see note's but I can't push them.</a>
        <a href="#no-push">I pushed a note but I don't see it on my device.</a>
        <a href="#security">What about security?</a>
      </ul>

      <section>
        <h5 id="lorem1">Why don't I see any notes?</h5>
        <p>
          If you signed in with your own Microsoft account, please ensure you have a section called "Quotes". 
          After adding a few pages to that section, ensure OneNote syncs so that you can see notes within Notifyer.
        </p>
        <p>
          If that doesn't work, you might be having cookie issues, try <a href="http://www.allaboutcookies.org/manage-cookies/clear-cookies-installed.html" target="_blank">clearing your cookies for this domain</a> (notifyer-quotes.herokuapp.com). Otherwise, get in touch.
        </p>
      </section>

      <section>
        <h5 id="lorem2">I see note's but I can't push them.</h5>
        <p>
          There might be a problem with your Pushbullet authorization. Try each of the following then try again:
        </p>
        <ul>
          <li>Clear your cookies for this site, then visit the <a href="/">homepage</a> and try logging into Pushbullet again.</li>
          <li>
            Check Pushbullet's <%= link_to "connected apps", @pushbullet_revoke_url, target: "_blank" %> page for a "Notifyer" entry. 
            If you see one, delete it, then visit the <a href="/">homepage</a> and try logging into Pushbullet again.
          </li>
        </ul>
        <p>
          If that doesn't work, you might be having cookie issues, try <a href="http://www.allaboutcookies.org/manage-cookies/clear-cookies-installed.html" target="_blank">clearing your cookies for this domain</a> (notifyer-quotes.herokuapp.com). Otherwise, get in touch.
        </p>
      </section>
      
      <section>
        <h5 id="no-push">I pushed a note but I don't see it on my device.</h5>
        <p>
          There seems to be a terrible lag for new Pushbullet installations on iOS devices, if you're using iOS, this might be the problem. 
          For best results, try installing <a href="https://chrome.google.com/webstore/detail/chlffgpmiacpedhhbkiomidkjlcfhogd" target="_blank">Pushbullet in Chrome</a> or on an <a href="https://play.google.com/store/apps/details?id=com.pushbullet.android" target="_blank">Android device</a>.
        </p> 
      </section>
       
       <section>
        <h5 id="security">What about security?</h5>
        <p>
          Notifyer accesses your accounts via vendor API's which use OAuth for authentication; 
          which is to say much of the safety is managed by <a href="https://docs.pushbullet.com/#oauth" target="_blank">Pushbullet</a> and
          <a href="https://msdn.microsoft.com/en-us/library/office/dn575435.aspx#sectionSection4" target="_blank">OneNote</a>. 
          All communication between Notifyer and vendor's are done over SSL.
        </p>
        <p>None of your information is stored by Notifyer.</p>
        <p>
          Once you're finished testing Notifyer be sure to revoke it's access on <%= link_to "Pushbullet", @pushbullet_revoke_url, target: "_blank" %> 
          and <%= link_to "OneNote", @onenote_revoke_url, target: "_blank" %> (if you used your own account).
        </p>
      </section>
    </div>
  </section>
</div>

app/views/notes/_notes.html.erb
<div class="mdl-layout__tab-panel is-active" id="notes">
  <% @notes.each do |note| %>
  <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
    <div class="mdl-card mdl-cell mdl-cell--12-col">
      <div class="mdl-card__supporting-text">
        <h4><%= note[:title] %></h4>
        <%= note[:body][:html] %>
      </div>
      <div class="mdl-card__actions">
        <%= form_tag push_note_path do %>
          <%= hidden_field_tag(:title, note[:title]) %>
          <%= hidden_field_tag(:body, note[:body][:text]) %>
          <%= hidden_field_tag(:url, note[:url]) %>
          <button type="submit" name="submit" value="push" <% if !@has_pb_access_token %>disabled<% end %> class="mdl-button mdl-button--accent mdl-js-ripple-effect">
            Push Note
          </button>
        <% end %>
      </div>
    </div>
<!--
    <button title="Push Note" type="submit" name="submit" value="push" <% if !@has_pb_access_token %>disabled<% end %> class="mdl-button mdl-js-button mdl-button--icon mdl-button--colored mdl-js-ripple-effect">
      <i class="material-icons">send</i>
    </button>
-->
  </section>
  <% end %>
</div>

app/views/notes/index.html.erb
<% provide(:title, 'Notes') %>
  <div class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header mdl-layout__header--scroll mdl-color--primary">
        <div class="mdl-layout--large-screen-only mdl-layout__header-row">
        </div>
        <div class="mdl-layout--large-screen-only mdl-layout__header-row">
          <h3>Notifyer</h3>
        </div>
        <div class="mdl-layout--large-screen-only mdl-layout__header-row">
        </div>
        <div class="mdl-layout__tab-bar mdl-js-ripple-effect mdl-color--primary-dark">
<!--          <a href="/" class="mdl-layout__tab">Home</a>-->
          <a href="#notes" class="mdl-layout__tab is-active">Notes</a>
          <a href="#help" class="mdl-layout__tab">Help</a>
          <a href="#about" class="mdl-layout__tab">About</a>
<!--
          <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-shadow--4dp mdl-color--accent" id="add">
            <i class="material-icons">add</i>
          </button>
-->
        </div>
      </header>
      
      <main class="mdl-layout__content">
        <%= render 'notes' %>
        <%= render 'help' %>
        <%= render 'about' %>
        <section class="section--footer mdl-grid" style="background-color: white"></section>
        <%= render 'partials/footer' %>
      </main>
    </div>
    <% if @has_pb_access_token %>
      <%= form_tag push_random_note_path do %>
        <button type="submit" name="submit" value="push" id="view-source" class="animated pulse infinite mdl-button mdl-js-button mdl-button--fab-mini mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
          <i class="material-icons">shuffle</i>
        </button>
        <div class="mdl-tooltip" for="view-source">
          Push Random Note
        </div>
      <% end %>
    <% end %>
  </div>

app/views/partials/_footer.html.erb
<footer class="mdl-mini-footer">
  <div class="mdl-mini-footer--left-section">
    <div class="mdl-logo_"><h5>Notifyer</h5></div>
    <ul class="mdl-mini-footer--link-list">
      <li><a href="http://byronbuckley.com">Byron Buckley</a></li>
      <li><a href="mailto:hello@byronbuckley.com">Contact</a></li>
<!--      <li><a href="#features">Logout</a></li>-->
<!--      <li><a href="#">Privacy &amp; Terms</a></li>-->
    </ul>
  </div>
</footer>

app/views/pushbullet/index.html.erb
<h1>Pushbullet#index</h1>
<p>Find me in app/views/pushbullet/index.html.erb</p>

app/views/pushbullet/push_note.html.erb
<h1>Pushbullet#push_note</h1>
<p>Find me in app/views/pushbullet/push_note.html.erb</p>

app/views/pushbullet/push_random_note.html.erb
<h1>Pushbullet#push_random_note</h1>
<p>Find me in app/views/pushbullet/push_random_note.html.erb</p>

app/views/welcome/callback.html.erb
 Live SDK Callback Page
 <script type="text/javascript">
     window.close();
 </script>

app/views/welcome/index.html.erb
<div class="demo-layout mdl-layout mdl-layout--fixed-header mdl-js-layout mdl-color--grey-100">
  <header class="demo-header mdl-layout__header mdl-layout__header--scroll mdl-color--grey-100 mdl-color-text--grey-800">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title">Notifyer</span>
      <div class="mdl-layout-spacer"></div>
    </div>
  </header>
  <div class="demo-ribbon mdl-color--primary"></div>
  <main class="demo-main mdl-layout__content">
    <div class="demo-container mdl-grid">
      <div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
      <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--8-col">

       <div class="mdl-card mdl-shadow--2dp mdl-card-wide">
          <div class="mdl-card__title" style="background-image: url(<%= asset_url('onenote_pushbullet.jpg') %>)">
                <h2 class="mdl-card__title-text">Welcome</h2>
          </div>
          <div class="mdl-card__supporting-text">
            <p>
              Are you the type to collect quotes that you rarely ever see again? <br>
              Use Notifyer to schedule the delivery of randomly selected quotes from your curated collection in OneNote. <br>
              Quotes are delivered via push notifications to your devices running Pushbullet.
            </p>
          </div>
          <div class="mdl-card__actions mdl-card--border">
            <a href="#onenote" class="mdl-button mdl-button--accent mdl-js-button mdl-js-ripple-effect">
              Get Started
            </a>
          </div>
<!--
          <div class="mdl-card__menu">
            <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
              <i class="material-icons">share</i>
            </button>
          </div>
-->
        </div>
         
        <br><br>
         
        <div class="flex-wrap">
         <div class="mdl-card mdl-card--custom mdl-card--onenote mdl-shadow--2dp flash-card_">
          <div id="onenote" class="mdl-card__title">
            <h3>
              OneNote
            </h3>
          </div>
          <div class="mdl-card__supporting-text  mdl-card--expand">
           <p>Sign in with the demo account. <br>
              u: notifyer at outlook dot com <br>
              p: nqLiveDem0
            </p>
            <p>Or sign into your own account. Make sure you have a "Quotes" section with a few pages in it.</p>
          </div>
          <div class="mdl-card__actions mdl-card--border">
              <button data-is-visible="<%= !@has_access_token %>" class="mdl-button mdl-button--full mdl-js-button mdl-js-ripple-effect" type="button" id="onenote_auth" onclick="Login('<%=raw(@auth_url)%>')">
                Authorize OneNote
              </button>
            <%= link_to "Revoke OneNote", @onenote_revoke_url, {:id => "onenote_revoke", "data-is-visible" => @has_access_token, :target => "_blank", :class => "mdl-button mdl-button--full mdl-js-button mdl-js-ripple-effect"} %>
          </div>
        </div>
         
         <div class="mdl-card--spacer">
           <i class="material-icons">add_circle</i>
         </div>
         
         <div class="mdl-card mdl-card--custom mdl-card--pushbullet mdl-shadow--2dp flash-card_">
          <div class="mdl-card__title">
            <h3>
              Pushbullet
            </h3>
          </div>
          <div class="mdl-card__supporting-text  mdl-card--expand">
            <ol>
              <li><a href="https://www.pushbullet.com/" target="_blank">Get an account.</a></li>
              <li>
                <a href="https://www.pushbullet.com/apps" target="_blank" id="get-a-pb-app">Get a Pushbullet App.</a>
                <div class="mdl-tooltip" for="get-a-pb-app">
                  For best results try the Chrome Extension or the Android app.
                </div>
              </li>
            </ol>
            <br>
            <p>If you already use Pushbullet you only need to authorize it.</p>
          </div>
          <div class="mdl-card__actions mdl-card--border">
            <%= link_to "Authorize Pushbullet", raw(@pushbullet_auth_url), {:id => "pb_auth", "data-is-visible" => !@has_pb_access_token, :class => "mdl-button mdl-button--full mdl-js-button mdl-js-ripple-effect"} %>
            <%= link_to "Revoke Pushbullet", raw(@pushbullet_revoke_url), {:id => "pb_revoke", "data-is-visible" => @has_pb_access_token, :target => "_blank", :class => "mdl-button mdl-button--full mdl-js-button mdl-js-ripple-effect"} %>
          </div>
        </div>
        </div>
        <br><br><br> 
        <div class="cta">
          <%= link_to "View Notes", notes_path, {"data-is-disabled" => !(@has_pb_access_token && @has_access_token), :id => "view-notes", :class => "mdl-button mdl-button--full mdl-button--large mdl-js-button mdl-button--raised mdl-button--accent mdl-js-ripple-effect"} %> 
        </div>
      </div>
    </div>
    <%= render 'partials/footer' %>
  </main>
</div>

app/views/welcome/pushbullet.html.erb
<h1>Notifyer</h1>
Insert comforting text and elevator music while redirecting.

app/views/welcome/submit.html.erb
<h1>OneNote Service API Result</h1>

<% if !@oneNoteWeb_url.nil? %>
    <b>Page created successfully!</b><br/><a href="<%=@oneNoteWeb_url%>" target="_onenote"> View created page on OneNote Online</a>
<% elsif !@response_code.nil? %>
    Error code: <%=@response_code%>    <br>
    Response headers: <%=@response_headers%>    
<% end %>
<p></p>
<br/>
<a href="/">&lt;- Go back</a>